spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/product-manager
    username: root
    password: Woozle33
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
